name: CI

on:
  push:
    branches: "master"
  pull_request:
    branches: "*"
jobs:
  build:
    name: ubuntu-latest ${{ matrix.config.go_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - go_version: 1.13
          - go_version: 1.14
    services:
      nacos:
        image: nacos/nacos-server:latest
        env:
          MODE: standalone
        ports:
          - "8848:8848"
          - "9848:9848"
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.config.go_version }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install goimports
      run: go get golang.org/x/tools/cmd/goimports

    - name: Test
      run: |
        diff -u <(echo -n) <(gofmt -d -s .)
        diff -u <(echo -n) <(goimports -d .)
        go test -race ./... -coverprofile=coverage.txt -covermode=atomic
        

    - name: Coverage
      run: bash <(curl -s https://codecov.io/bash)


